const initGemini = require('../config/gemini');

let geminiModel = null;
let isGeminiConfigured = false;

/**
 * Initialize Gemini on first use
 */
const ensureInitialized = () => {
  if (geminiModel === null && !isGeminiConfigured) {
    const { model, isConfigured } = initGemini();
    geminiModel = model;
    isGeminiConfigured = isConfigured;
  }
};

/**
 * Generate risk profile for a worker using Gemini AI
 * @param {{ name: string, platform: string, zone: Object, avgWeeklyEarnings: number, workingDaysPerWeek: number, workingHoursPerDay: number }} workerData
 * @returns {Promise<{ riskScore: number, riskProfile: string }>}
 */
const generateRiskProfile = async (workerData) => {
  ensureInitialized();

  if (!isGeminiConfigured || !geminiModel) {
    return generateFallbackRiskProfile(workerData);
  }

  try {
    const prompt = `You are a risk assessment AI for Insurly, a parametric income insurance platform for food delivery workers in Bhubaneswar, India. 
    
Analyze this worker's profile and respond ONLY in valid JSON with no markdown formatting, no code blocks, no backticks. 

Required JSON fields:
- riskScore: number between 0-100 (higher = more risk-prone to disruptions)
- riskProfile: string with 2-3 sentences explaining the risk assessment

Worker Data:
- Name: ${workerData.name}
- Platform: ${workerData.platform}
- Zone: ${workerData.zone?.area || 'Unknown'}, ${workerData.zone?.city || 'Bhubaneswar'}
- Average Weekly Earnings: Rs ${workerData.avgWeeklyEarnings}
- Working Days/Week: ${workerData.workingDaysPerWeek}
- Working Hours/Day: ${workerData.workingHoursPerDay}

Consider zone-specific risks (flooding, heat exposure), working hours exposure, and platform-specific patterns.`;

    const result = await geminiModel.generateContent(prompt);
    const responseText = result.response.text();

    // Try to parse JSON from response
    const jsonMatch = responseText.match(/\{[\s\S]*?\}/);
    if (jsonMatch) {
      const parsed = JSON.parse(jsonMatch[0]);
      return {
        riskScore: Math.max(0, Math.min(100, parsed.riskScore || 50)),
        riskProfile: parsed.riskProfile || 'Risk profile generated by AI'
      };
    }

    return generateFallbackRiskProfile(workerData);
  } catch (error) {
    console.error(`[${new Date().toISOString()}] ❌ Gemini risk profile error:`, error.message);
    return generateFallbackRiskProfile(workerData);
  }
};

/**
 * Analyze a claim for fraud using Gemini AI
 * @param {{ claimData: Object, workerHistory: Object, antiSpoofingChecks: Array }} params
 * @returns {Promise<{ fraudScore: number, signals: string[], recommendation: string, explanation: string }>}
 */
const analyzeFraud = async ({ workerData, claimData, antiSpoofingChecks }) => {
  ensureInitialized();

  if (!isGeminiConfigured || !geminiModel) {
    return generateFallbackFraudAnalysis(antiSpoofingChecks);
  }

  try {
    const prompt = `You are an insurance fraud detection AI for Insurly, a parametric income insurance platform for food delivery workers in India. Analyze this claim data and respond ONLY in valid JSON with no markdown formatting, no code blocks, no backticks.

Required JSON fields:
- fraudScore: number 0-100 (0 = no fraud, 100 = definite fraud)
- signals: array of strings listing detected fraud signals
- recommendation: string, one of: "auto_approve", "conditional_approve", "manual_review"
- explanation: string with detailed fraud analysis explanation

Claim Data: ${JSON.stringify(claimData)}
Worker History: ${JSON.stringify(workerHistory)}
Rule-based Fraud Checks: ${JSON.stringify(antiSpoofingChecks)}`;

    const result = await geminiModel.generateContent(prompt);
    const responseText = result.response.text();

    const jsonMatch = responseText.match(/\{[\s\S]*?\}/);
    if (jsonMatch) {
      const parsed = JSON.parse(jsonMatch[0]);
      return {
        fraudScore: Math.max(0, Math.min(100, parsed.fraudScore || 0)),
        signals: Array.isArray(parsed.signals) ? parsed.signals : [],
        recommendation: ['auto_approve', 'conditional_approve', 'manual_review'].includes(parsed.recommendation)
          ? parsed.recommendation : 'conditional_approve',
        explanation: parsed.explanation || 'AI analysis completed'
      };
    }

    return generateFallbackFraudAnalysis(antiSpoofingChecks);
  } catch (error) {
    console.error(`[${new Date().toISOString()}] ❌ Gemini fraud analysis error:`, error.message);
    return generateFallbackFraudAnalysis(antiSpoofingChecks);
  }
};

/**
 * Generate disruption prediction for the next week using Gemini
 * @param {{ currentWeather: Object, recentEvents: Array, zoneData: Object }} params
 * @returns {Promise<{ prediction: string, confidence: number, risks: string[] }>}
 */
const generatePrediction = async ({ currentWeather, recentEvents, zoneData }) => {
  ensureInitialized();

  if (!isGeminiConfigured || !geminiModel) {
    return {
      prediction: 'Unable to generate AI prediction — Gemini API not configured. Based on historical patterns, moderate disruption risk expected.',
      confidence: 45,
      risks: ['Weather variations possible', 'Monitor AQI levels']
    };
  }

  try {
    const prompt = `You are a weather disruption prediction AI for food delivery workers in Bhubaneswar, India. Predict disruption risk for the next 7 days. Respond ONLY in valid JSON with no markdown. Required fields: prediction (string 2-3 sentences), confidence (number 0-100), risks (array of strings max 5 items).

Current Weather: ${JSON.stringify(currentWeather)}
Recent Disruption Events (last 30 days): ${JSON.stringify(recentEvents)}
Zone Risk Data: ${JSON.stringify(zoneData)}`;

    const result = await geminiModel.generateContent(prompt);
    const responseText = result.response.text();

    const jsonMatch = responseText.match(/\{[\s\S]*?\}/);
    if (jsonMatch) {
      const parsed = JSON.parse(jsonMatch[0]);
      return {
        prediction: parsed.prediction || 'Moderate risk expected',
        confidence: Math.max(0, Math.min(100, parsed.confidence || 50)),
        risks: Array.isArray(parsed.risks) ? parsed.risks : []
      };
    }

    return { prediction: 'Analysis inconclusive', confidence: 40, risks: [] };
  } catch (error) {
    console.error(`[${new Date().toISOString()}] ❌ Gemini prediction error:`, error.message);
    return { prediction: 'Prediction unavailable', confidence: 0, risks: [] };
  }
};

/**
 * Rule-based fallback for risk profile generation
 * @param {Object} workerData
 * @returns {{ riskScore: number, riskProfile: string }}
 */
const generateFallbackRiskProfile = (workerData) => {
  const zoneRiskScores = {
    'Patia': 75, 'Nayapalli': 65, 'Saheed Nagar': 60,
    'Khandagiri': 55, 'Rasulgarh': 70, 'Unit-4': 50, 'Chandrasekharpur': 45
  };

  const baseScore = zoneRiskScores[workerData.zone?.area] || 55;
  const hoursAdjust = workerData.workingHoursPerDay > 10 ? 5 : 0;
  const earningsAdjust = workerData.avgWeeklyEarnings > 2500 ? -5 : 5;
  const riskScore = Math.max(0, Math.min(100, baseScore + hoursAdjust + earningsAdjust));

  const riskProfile = `Worker in ${workerData.zone?.area || 'Unknown'} zone with ${workerData.workingHoursPerDay}h daily exposure. Zone has ${baseScore > 60 ? 'elevated' : 'moderate'} historical disruption risk. ${workerData.platform === 'zomato' ? 'Zomato' : 'Swiggy'} partner with Rs ${workerData.avgWeeklyEarnings} weekly earnings.`;

  return { riskScore, riskProfile };
};

/**
 * Rule-based fallback for fraud analysis
 * @param {Array<{ name: string, triggered: boolean, scoreIncrease: number }>} antiSpoofingChecks
 * @returns {{ fraudScore: number, signals: string[], recommendation: string, explanation: string }}
 */
const generateFallbackFraudAnalysis = (antiSpoofingChecks) => {
  let fraudScore = 0;
  const signals = [];

  for (const check of antiSpoofingChecks) {
    if (check.triggered) {
      fraudScore += check.scoreIncrease;
      signals.push(check.name);
    }
  }

  fraudScore = Math.min(100, fraudScore);

  let recommendation = 'auto_approve';
  if (fraudScore >= 70) recommendation = 'manual_review';
  else if (fraudScore >= 31) recommendation = 'conditional_approve';

  const explanation = signals.length > 0
    ? `Rule-based analysis detected ${signals.length} fraud signal(s): ${signals.join(', ')}. Total fraud score: ${fraudScore}/100.`
    : 'No fraud signals detected by rule-based analysis. Claim appears legitimate.';

  return { fraudScore, signals, recommendation, explanation };
};

module.exports = {
  generateRiskProfile,
  analyzeFraud,
  generatePrediction
};
